### ISSUE TITLE
Add a constants_user.hxx file that is not tracked which overrides constants.hxx

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#10]
I have customized my constants.hxx, but every time the upstream code is updated, I have to stash my changes (I don't commit them because I keep the local code free of my changes).

Please add an option to have constants_user.hxx (untracked) which would override default constants.hxx.

**Comment by TrainzLuvr** [comment]
Hmm, so how to now override some of the constants.hxx values since they were all declared as static constexpr?

**Comment by atanisoft** [comment]
> how to now override some of the constants.hxx values since they were all declared as static constexpr?

It wasn't originally designed for user overrides as it was originally designed for static compilation. Let me adjust the approach being used so it is easier to override (via the constants_user.hxx file)

**Comment by TrainzLuvr** [comment]
My bad, I should've been more clear what I was asking for.

The idea is to override things like PIN, WIFI_MODE, SSDI/AP values to allow users to customize their own, while retaining the ability to pull the latest source.

**Comment by atanisoft** [comment]
I understood what you were after but didn't think of the issue you would face like this:
```
In file included from ../main/constants.hxx:161,
                 from ../main/hardware.hxx:43,
                 from ../main/esp32olcbhub_stack.cpp:37:
../main/constants_user.hxx:3:29: error: redefinition of 'constexpr const gpio_num_t LED_WIFI_PIN'
 static constexpr gpio_num_t LED_WIFI_PIN = GPIO_NUM_31;
                             ^~~~~~~~~~~~
In file included from ../main/hardware.hxx:43,
                 from ../main/esp32olcbhub_stack.cpp:37:
../main/constants.hxx:64:29: note: 'constexpr const gpio_num_t LED_WIFI_PIN' previously defined here
 static constexpr gpio_num_t LED_WIFI_PIN = GPIO_NUM_22;
                             ^~~~~~~~~~~~
```
I may need to switch to using `#define ... ` instead but was hoping not to...

**Comment by TrainzLuvr** [comment]
Yes, that's what I also got, and I thought I was doing something wrong... :)

**Comment by atanisoft** [comment]
not really wrong, just not how it was intended to work or be used... I'll have a fix shortly.

**Comment by TrainzLuvr** [comment]
If you think it's better to keep it, then leave it be.

I somewhat understand the benefit of using constexpr (compile-time constant, more optimized) but the drawback is...constant. :)

**Comment by atanisoft** [comment]
I'm going to convert it to sdkconfig entries (similar to the CS) for a few of the entries. Most of constants.hxx will go away.

**Comment by TrainzLuvr** [comment]
The new sdkconfig appears to be working so far.
