### ISSUE TITLE
Changing Node ID in WebUI has no effect-fails

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#12]
I went to test changing Node ID from the WebUI, and the expected outcome should've been accepted new ID, and reboot of the node, but instead a JavaScript error popped up in the console:

```
Uncaught ReferenceError: ip is not defined
    at save_node_id (index.html:356)
    at HTMLButtonElement.onclick (VM69 index.html:186)
save_node_id @ index.html:356
onclick @ VM69 index.html:186
```

Node ID did not change suffice to say. The spinning circle kept spinning... :)

**Comment by atanisoft** [comment]
be sure to remove web/index.html.gz before uploading the next build.

**Comment by TrainzLuvr** [comment]
The latest update fixes this issue.

There is now another one, though not sure if it's persistant or one-off.

**Comment by atanisoft** [comment]
node-id should be persistent unless you run a factory reset (10sec GND on pin 15) which will reset everything to compiled settings.

**Comment by TrainzLuvr** [comment]
I was referring to #14

**Comment by atanisoft** [comment]
Gotcha, the websocket code needs a bit more tweaking all the same. I'll use #14 to track that work.
