### ISSUE TITLE
WebSocket lingers?

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#14]
Went to CDI and changed the node's description. Then went back to the WebUI and clicked on Refresh for the node description field.

Browser console reported:

```
WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ index.html:702
La | @ | cash.min.js:26
```

Suffice to say, it did not refresh the field.

Also I noticed that it takes a bit longer again to load the WebUI and initially update some fields.

**Comment by atanisoft** [comment]
nothing has changed in the web code but it looks like the websocket is not reconnecting when it needs to. I suspect there is something in the sdkconfig that we will need to tweak to improve the responsiveness.
