### ISSUE TITLE
Changing node ID and saving causes failure to reboot

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#17]
```
[NVS] Loading configuration
[NVS] Setting Node ID to: 50201030001
[Reboot] 1750 ms remaining until reboot
[Reboot] 1500 ms remaining until reboot
[Reboot] 1250 ms remaining until reboot
[Reboot] 1000 ms remaining until reboot
[Reboot] 750 ms remaining until reboot
[Reboot] 500 ms remaining until reboot
[Reboot] 250 ms remaining until reboot
[Reboot] Stopping config file sync handler...
[Httpd] Shutting down webserver
[httpd] Shutting down HTTP listener
Shutdown listening socket 80.
[mDNS] Removing advertisement of _http._tcp.
[httpd] Shutting down HTTP listener
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:1,suc:4,fail:0) bus (arb-err:0,err:31,state:Err-Warn)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:1,suc:4,fail:0) bus (arb-err:0,err:31,state:Err-Warn)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:12 (pending:1,suc:4,fail:0) bus (arb-err:0,err:31,state:Err-Warn)
```

And then nothing...node is still up but all services shut off, and WebUI inaccessible. It should've rebooted.

**Comment by TrainzLuvr** [comment]
I should add that the value did save (verified after manual reset).

There were no crashes or errors.

**Comment by TrainzLuvr** [comment]
Also, I'm curious, changing Node ID affects the rest of the configuration?

When I changed the ID and reset manually, my other settings went back to defaults.

Is the Node ID a parent of everything else, so each ID has its own separate configuration tree?

**Comment by TrainzLuvr** [comment]
I set the Node ID back to 00 and my old config was gone, so changing Node ID definitely resets the configuration to defaults.

Not sure if that is a bug or an intended behaviour, but it should be noted somewhere.

**Comment by atanisoft** [comment]
Resetting Node ID will force a factory reset on next boot. The reboot failure was due to the addition of http shutdown, I'll need to debug that as I wasn't seeing that specific failure in my tests but it is likely something simple.

**Comment by atanisoft** [comment]
> the WebUI feels much snappier now. :)

Make a couple minor tweaks to the default config settings (reduce WS timeout to 5msec from 200msec) and adjusted the select() timeouts to correct the calculations.
