### ISSUE TITLE
Problem cloning this repo and its submodules

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#2]
I always clone anonymously, through https:

git clone --recurse-submodules https://github.com/atanisoft/esp32olcbhub.git
Cloning into 'esp32olcbhub'...
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 100 (delta 36), reused 55 (delta 20), pack-reused 0
Receiving objects: 100% (100/100), 58.39 KiB | 980.00 KiB/s, done.
Resolving deltas: 100% (36/36), done.
Submodule 'components/HttpServer' (git@github.com:atanisoft/HttpServer.git) registered for path 'components/HttpServer'
Submodule 'components/OpenMRNLite' (git@github.com:atanisoft/OpenMRNIDF.git) registered for path 'components/OpenMRNLite'
Submodule 'components/esp_littlefs' (https://github.com/joltwallet/esp_littlefs.git) registered for path 'components/esp_littlefs'
Cloning into 'XXX/esp32olcbhub/components/HttpServer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:atanisoft/HttpServer.git' into submodule path 'XXX/esp32olcbhub/components/HttpServer' failed
Failed to clone 'components/HttpServer'. Retry scheduled
Cloning into 'XXX/esp32olcbhub/components/OpenMRNLite'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:atanisoft/OpenMRNIDF.git' into submodule path 'XXX/esp32olcbhub/components/OpenMRNLite' failed
Failed to clone 'components/OpenMRNLite'. Retry scheduled
Cloning into 'XXX/esp32olcbhub/components/esp_littlefs'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 341 (delta 1), reused 2 (delta 0), pack-reused 330
Receiving objects: 100% (341/341), 96.52 KiB | 1.12 MiB/s, done.
Resolving deltas: 100% (224/224), done.
Cloning into 'XXX/esp32olcbhub/components/HttpServer'...
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:atanisoft/HttpServer.git' into submodule path 'XXX/esp32olcbhub/components/HttpServer' failed
Failed to clone 'components/HttpServer' a second time, aborting

**Comment by atanisoft** [comment]
Sorry about that, the .gitmodules file had `git@github.com:...` instead of `https://github.com/....`. I've pushed an update that should fix it.

**Comment by TrainzLuvr** [comment]
Thanks.
