### ISSUE TITLE
Add an ability to change the WiFi channel through firmware defaults and in the CDI

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#20]
We've talked about it before, and it's presently hard-coded at https://github.com/atanisoft/esp32olcbhub/blob/main/main/esp32olcbhub_stack.cpp#L178 to Ch 1.

Also adding a drop-down in the CDI for this in the WiFi section would be useful for many users.

**Comment by atanisoft** [comment]
Exposing the WiFi config in CDI would be nice but will have potential drawbacks for compile time config. Will need to evaluate how to expose it.
