### ISSUE TITLE
WPA settings via WebUI do not save to the /fs/config; httpd shuts off upon save.

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#21]
Latest pull, all submodules updated, flash erased prior to flashing.

I went to change the settings from WPA/WPA2 to WPA2/WPA3 then click Save. For whatever reason the httpd shutdown.

```
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4,fail:0) bus (arb-err:0,err:24,state:Err-Warn)
[WiFi] Mode:Station + SoftAP (3) Station: *****, SoftAP: esp32olcbhub (auth:**WPA2/WPA3**, channel:11), hostname:esp32olcbhub_50201030000 uplink:Yes (auto:_openlcb-can._tcp,manual::12021) tx:78 sleep:No hub:No (_openlcb-can._tcp:12021) SNTP:No (server:pool.ntp.org, timezone:EST5EDT)
[Httpd] Shutting down webserver
[httpd] Shutting down HTTP listener
Shutdown listening socket 80.
[mDNS] Removing advertisement of _http._tcp.
[httpd] Shutting down HTTP listener
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4,fail:0) bus (arb-err:0,err:24,state:Err-Warn)
00:00:40.294: Free heap: 183.38kB (max block size: 111.12kB), mainBufferPool: 0.62kB, Hub clients: 0, FreeRTOS tasks: 16
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4,fail:0) bus (arb-err:0,err:24,state:Err-Warn)
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4,fail:0) bus (arb-err:0,err:24,state:Err-Warn)
```

I rebooted the Hub.

```
[SNIP] version:4, manufacturer:http://atanisoft.github.io/esp32olcbhub, model:ESP32OlcbHub, hw-v:1.0.0, sw-v:64c1dcf
Creating config file /fs/config
[Httpd] Initializing webserver
00:00:10.292: Free heap: 273.64kB (max block size: 111.12kB), mainBufferPool: 0.15kB, Hub clients: 0, FreeRTOS tasks: 8
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:0,fail:0) bus (arb-err:0,err:0,state:Bus Off)
[TWAI] Enabling TWAI device:twai0 mode:cf1cd949 (non-blocking)
[WiFi] Mode:Station + SoftAP (3) Station: ********, SoftAP: esp32olcbhub (auth:**WPA/WPA2**, channel:11), hostname:esp32olcbhub_50201030000 uplink:Yes (auto:_openlcb-can._tcp,manual::12021) tx:78 sleep:No hub:No (_openlcb-can._tcp:12021) SNTP:No (server:pool.ntp.org, timezone:EST5EDT)
```
Back to WPA/WPA2 and it seems to be recreating the /fs/config when it shouldn't.

Also it seems to be doing this each time it boots:

```
[NVS] Initializing NVS
[NVS] Loading configuration
Event ID reset in 5 seconds, factory reset in 10 seconds.
Event ID reset in 4 seconds, factory reset in 9 seconds.
Event ID reset in 3 seconds, factory reset in 8 seconds.
Event ID reset in 2 seconds, factory reset in 7 seconds.
Event ID reset in 1 seconds, factory reset in 6 seconds.
Factory reset in 5 seconds.
Factory reset in 4 seconds.
Factory reset in 3 seconds.
Factory reset in 2 seconds.
Factory reset in 1 seconds.
Factory reset triggered!
[NVS] Initializing default configuration
[FS] 756.43/757.66 kb space used
[SNIP] version:4, manufacturer:http://atanisoft.github.io/esp32olcbhub, model:ESP32OlcbHub, hw-v:1.0.0, sw-v:64c1dcf
Creating config file /fs/config
```

I don't believe it should.

**Comment by atanisoft** [comment]
Httpd shutdown is expected since the wifi code is only loaded on startup.

The factory reset pin needs to be pulled high (SVN pin) during startup. Use a 10k R to 3v3.

**Comment by TrainzLuvr** [comment]
Yeah but if I save a setting, it should not kill my only way of changing them (WebUI). If it needs to restart the httpd that's fine, but it should definitely not stop the httpd after a setting is saved. That only forces a users to reboot the node to get it back, which is not acceptable UX.

**Comment by atanisoft** [comment]
Agreed, the hub code needs to be updated to be similar to the io board where it defers the "update complete" message from being sent. I'll get that updated tomorrow, in the meantime you can enable the hub and connect from jmri to set other settings since it will not send the update complete until you close the window or trigger it manually.

**Comment by TrainzLuvr** [comment]
That's the thing though, I can't make the settings "stick" even from the JMRI either.

Is that because I don't have have a PU R on the factory reset pin?

**Comment by atanisoft** [comment]
Likely yes, if the pin is not high it will erase the config and force recreate from defaults.

**Comment by atanisoft** [comment]
This appears to be due to the Factory Reset pin being left floating. As part of https://github.com/atanisoft/esp32olcbhub/issues/24 I've reverted to using pin 15 by default for the Factory Reset since that has a pull-up on it. I've also noted in the help text for using the https://github.com/atanisoft/esp32olcbio PCB that it should be set to pin 39 instead.
