### ISSUE TITLE
Updating any setting via WebUI causes the data loss in the UI

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#22]
I went to turn the Hub On and Uplink Off. Clicked Save on both.

Followed with CTRL+F5 to cause a refresh in my browser and the configuration did not load back, leaving most of the fileds empty. Instead, animated spinners are visible next to all of the buttons.

**Comment by atanisoft** [comment]
Can you check the browser console to see if there is an error listed? I suspect it is the websocket issue that is tracked on the HttpServer which is next on my list to fix.

**Comment by TrainzLuvr** [comment]
I did not see any errors in the console. It shows the data that's supposed to be in the fields.

**Comment by atanisoft** [comment]
Ok, this might be related to #21. Once I get that fixed we can debug this further.

**Comment by atanisoft** [comment]
@TrainzLuvr With the latest code the updates sent via web (or JMRI CDI) will require clicking the "Update Complete" button to persist the config updates. This should allow you to reconfigure the node without having it reboot after an update via the web interface.

**Comment by TrainzLuvr** [comment]
I usually did follow those steps regardless: change values, write, Update Complete, Reboot every time but that might have been excessive and unnecessary. 

Is this normal behaviour for LCC nodes (having to click Update Complete)? I don't recall that being the case.

**Comment by atanisoft** [comment]
JMRI will send the update complete upon closing of the CDI window. From the web interface there is no hook point to trigger this call other than a button.

**Comment by TrainzLuvr** [comment]
I meant JMRI because you said above that Update Complete will have to be clicked on going forward so I assumed I would have to do it in JMRI.

For the WebUI, could you not send Update Complete each time a value is saved, since it's using sockets to communicate?

**Comment by atanisoft** [comment]
The update complete is what caused the reboot to occur, change SSID and it reboots, change pw and it reboots. It would not be an ideal UX so the deferring of the update complete to a button provides a better UX but still not 100% ideal. I don't have a good solution just yet for firing that event from the web.
