### ISSUE TITLE
Node still hangs after updating settings for Hub (off->on)/Uplink (on->off) via WebUI

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#29]
Clean build, clean flash.

Went to enable Hub, disable Uplink - save both params then Update Complete.

WebUI stuck trying to refresh all the values. Serial Monitor does not indicate any issues, and nothing in the browser Console either.

**Comment by TrainzLuvr** [comment]
This appears to have something to do with enabling the Hub?

I rebooted and then went to change TXPower parameter, saved and Update Complete. Force-refreshed the browser page and all fine. Then went to disable Hub and enable Uplink, save, Update Complete, again fine after force-refreshing the page.

Now the Hub was disabled and Uplink enabled, so I went to enable Hub and disable Uplink, save both, Update Complete. This time force-refresh hung the page tryint to refresh values.

**Comment by atanisoft** [comment]
It sounds like you might still be hitting the factory reset issues. I can't reproduce the issue you are reporting here otherwise

**Comment by atanisoft** [comment]
Or you may have run into the websocket closed issue. It's on my short list to fix.

**Comment by atanisoft** [comment]
After fixing https://github.com/atanisoft/HttpServer/issues/9 I'm not able to reproduce this.
