### ISSUE TITLE
Unable to switch to APSTA mode

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#3]
I edited the code to make the APSTA default instead of AP; I've defined DEFAULT_STA_SSID / DEFAULT_STA_PASS in constants.hxx; edited the nvs_config.cpp with:

```
strcpy(config->sta_ssid, DEFAULT_STA_SSID);
strcpy(config->sta_pass, DEFAULT_STA_PASS);
strcpy(config->ap_ssid, DEFAULT_AP_NAME);
strcpy(config->ap_pass, DEFAULT_AP_PASS);
```

But it still keeps making SoftAP only - seems that the configuration is defaulting from inside the chip somewhere.

**Comment by TrainzLuvr** [comment]
I see about the Factory Reset...I read the constants.hxx that needs to be held for 10 sec. I thought it was instant.

And this was all my idea, LOL!

**Comment by TrainzLuvr** [comment]
This https://github.com/atanisoft/esp32olcbhub/blob/f1bd48a1a335fd0d75b747cf0f39e5aefef698c8/main/nvs_config.cpp#L229 should be **default_config(&config);**

**Comment by TrainzLuvr** [comment]
It looks like the WiFi code needs to be reworked a bit, so there's correct discernment between STA and AP. I had to key in my home WiFi password to connect to the SoftAP, rather than the default esp32olcbhub.

But that's partially my fault because I injected the STA values into the config without reworking the rest of the code, since I could not connect to the WebUI to reconfigure it any other way.

I think there should be an option in constants.hxx to enable the Hub by default.

**Comment by TrainzLuvr** [comment]
I see the error of my ways...I'll split this into multiple issues.

**Comment by atanisoft** [comment]
> This
> 
> https://github.com/atanisoft/esp32olcbhub/blob/f1bd48a1a335fd0d75b747cf0f39e5aefef698c8/main/nvs_config.cpp#L229
> 
> should be
> `default_config(&config);`

This is deferring the actual factory reset until the next restart, this is triggered from the web interface only typically.

> I think there should be an option in constants.hxx to enable the Hub by default.

That would be good to split off into it's own issue I think since it would need some tweaks in the OpenMRN CDI definition.

> But it still keeps making SoftAP only - seems that the configuration is defaulting from inside the chip somewhere.

The config is stored in NVS, it can be cleared via `idf.py erase_flash` or via factory reset pin being held LOW during startup (once I verify https://github.com/atanisoft/esp32olcbhub/issues/5).

> It looks like the WiFi code needs to be reworked a bit, so there's correct discernment between STA and AP.

Yeah, it is not ideal right now for sure. I'll add a couple entries to `constants.hxx` for SSID/PASS so it can be reconfigured at compile time.

**Comment by atanisoft** [comment]
Please test the latest, you will need to run "git submodule update" to pull the latest bits in for the dependencies as they have been updated as well. A couple fixes are going to be pushed over to the CS as well based on this update.

**Comment by TrainzLuvr** [comment]
Still not working.

I go to connect my UWT-100 to the "esp32olcbhub" network, and put the same as password, and I get back "Wrong WiFi password".

My constants.hxx have not been changed for _AP_NAME/PASS, only set the WIFI_MODE_APSTA, and including the _SSID_NAME/PASS.

The board connects to my SSID and I can access the WebUI (UI feels/load faster now).

**Comment by atanisoft** [comment]
WebUI has been reworked a bit to improve load time (it was way too slow on the esp32 but was fast on esp32s2, go figure).

I'll do some more testing but it should be working unless there is a bug on the UWT (will confirm with mine in a bit).

**Comment by TrainzLuvr** [comment]
I got my UWT-100 to assert crash a few times, too. :)

**Comment by atanisoft** [comment]
@TrainzLuvr found the issue, the Esp32WiFiManager update in 09df49e had an incorrect check for SoftAP PW being empty when it should have been not empty.

**Comment by TrainzLuvr** [comment]
I can confirm that WiFi is now working correctly.

But the other ugly issue (LwIP) has come up again:

```
Incoming connection from 192.168.4.2, fd 51.
[TWAI] RX:0 (pending:0,overrun:0,discard:0) TX:34 (pending:0,suc:34,fail:0) bus (arb-err:0,err:0,state:Running)
GCHubPort: Shutting down gridconnect port -1. (0x3ffdb338)
Incoming connection from 192.168.4.2, fd 51.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x40127361  PS      : 0x00060830  A0      : 0x80117290  A1      : 0x3ffc97b0  
A2      : 0x3ffbd848  A3      : 0x31753263  A4      : 0x0000ffff  A5      : 0x0000ffff  
A6      : 0x3ffdb0f0  A7      : 0x3ffdae30  A8      : 0x00080000  A9      : 0x3ffc9790  
A10     : 0x3ffdb0f0  A11     : 0x0000059b  A12     : 0x3ffc89d8  A13     : 0x00000000  
A14     : 0x3ffc8a14  A15     : 0x00000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00080008  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace:0x4012735e:0x3ffc97b0 0x4011728d:0x3ffc97d0

0:  0x4011728d: tcpip_thread_handle_msg at C:/espressif/esp-idf/components/lwip/lwip/src/api/tcpip.c:208
  \-> inlined by: tcpip_thread at C:/espressif/esp-idf/components/lwip/lwip/src/api/tcpip.c:154
```
As a result, the Hub isn't working properly (crashed)? and the throttle can't connect to LCC, I keep seeing:
```
Searching for LCC...
Connecting to LCC/a..
Reconnecting...
```
Just can't win... :(

**Comment by atanisoft** [comment]
Can you add that backtrace to the other issue tracking LwIP crashes? I think this is a failed allocation of a pbuf and may be fixed by tweaking the sdkconfig settings a bit

**Comment by TrainzLuvr** [comment]
UWT-100 froze, crashed and shut down now, LOL. I think I need to file a bug report somewhere with TCS.
