### ISSUE TITLE
Factory Reset does not appear to work

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/esp32olcbhub#5]
I thought to do a Factory Reset, I defined Pin 2 for that, and connecting it to the GND does not produce any noticable effect in the serial monitor.

I had it connected to the GND and resetted the ESP32.

**Comment by atanisoft** [comment]
GPIO 2 has a hardware pull-down so it is not a good selection. I'd suggest 15 (has pull-up) or 16 (no pull up or down).

I'll do some further testing on it as well.

**Comment by TrainzLuvr** [comment]
I put it on 16, pull it to the GND and hold, reset, nothing...

**Comment by TrainzLuvr** [comment]
It also appears that flashing the firmware does not erase NVS settings, because I can't connect with the default password even after reflashing.

**Comment by atanisoft** [comment]
`idf.py erase_flash ; idf.py flash monitor`

I'll do some testing on the factory reset and see what I can come up with.

**Comment by atanisoft** [comment]
This looks to be the same type of issue as seen with TWAI not enabling due to compile time constant checking. I'll adjust it to define the pin by default to GPIO 15 (since it has a pull-up) and removing the `#if ... / #else` piece from `hardware.hxx`

**Comment by atanisoft** [comment]
This has been fixed in the latest code using GPIO 15 by default since it typically has a pull-up on the board. Pulling to GND for 5sec during startup will reset events (really a no-op on the hub) or 10sec and it will revert all config settings to defaults from `constants.hxx`.
