### ISSUE TITLE
Hub node disappears from JMRI node list

### ISSUE THREAD

**Issue by atanisoft** [atanisoft/esp32olcbhub#9]
```
[TWAI] RX:682 (pending:0,overrun:89,discard:0) TX:934 (pending:0,suc:934,fail:0) bus (arb-err:220,err:0,state:Running)
[TWAI] RX:688 (pending:0,overrun:89,discard:0) TX:936 (pending:0,suc:936,fail:0) bus (arb-err:220,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[HealthMon 00:12:30] Free heap: 162.70kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.60kB
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[HealthMon 00:14:00] Free heap: 162.70kB (max block size: 111.12kB), Free PSRAM: 0.00kB (max block size: 0.00kB), mainBufferPool: 2.60kB
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
[TWAI] RX:729 (pending:0,overrun:123,discard:0) TX:1008 (pending:0,suc:1008,fail:0) bus (arb-err:254,err:0,state:Running)
```
It literally hung my Configure Nodes window in JMRI when I clicked Refresh and all nodes disappeared. I closed and re-opened the window, but clicking Refresh causes all nodes to disappear again. JMRI is really confused it seems, maybe it's a bug in it as well. :)

_Originally posted by @TrainzLuvr in https://github.com/atanisoft/esp32olcbhub/issues/7#issuecomment-723386426_

**Comment by atanisoft** [comment]
@TrainLuvr Was JMRI connected via CAN or TCP/IP? I've been refreshing the nodelist in JMRI while connected via CAN and it doesn't seem to ever disappear fully (if it does it returns after a second or two)

**Comment by TrainzLuvr** [comment]
It is via CAN using JMRI 4.18+R37ad3d0 with LCC Buffer-USB and the rest of my test nodes. I used to run JMRI 4.21, then went to JMRI 4.20, and now down to JMRI 4.18, because I got an impression that this issue was worse in higher versions.

JMRI 4.18 appears to have an acceptable level of discomfort, but it still happens, so it's probably not JMRI, idk.

**Comment by atanisoft** [comment]
Ok, it may be that I don't have enough nodes on the bus. I'll see if I can wire up a few more and keep testing

**Comment by TrainzLuvr** [comment]
The current setup is a Tiva CS, Railcom board, ESP32olcbhub. Previously I was testing using ESP32CS and Railcom board.

So, it could be either the ESP32 or the Railcom board being the two constants, but I put my money on the ESP32. ;)

**Comment by atanisoft** [comment]
My network is pretty small currently, esp32olcbhub, esp32s2io, jmri. I'll need to setup another esp32 or two and find cables for them and do some more tests.

My guess is packet overrun causing a refresh packet to go into the ether

**Comment by TrainzLuvr** [comment]
For really short distances you don't need full Ethernet cables - take wires from a CAT5e/6 and connect that way (CAN_H/L + CAN_GND), just make sure they are > 10" long and terminate with a 120 ohm resistor across CAN_H/L on the last node.

I got everything breadboarded and things are floating in mid-air. :rofl:

**Comment by atanisoft** [comment]
Yeah, that is how I have a couple boards on my desk. I'll need to get out a couple breadboards and put some components on it.

**Comment by atanisoft** [comment]
> I closed and re-opened the window, but clicking Refresh causes all nodes to disappear again. JMRI is really confused it seems, maybe it's a bug in it as well. :)

I was able to reproduce this behavior and it looks more likely to be a JMRI bug than a bug in the TWAI driver code. I'm seeing a few buffer overruns still but in all cases I can see the responses showing up in the LCC Traffic Monitor in JMRI but the JMRI network window is blank (even the JMRI node is gone!).

**Comment by TrainzLuvr** [comment]
There must be some regression in the code because to me it was getting worse from 4.18->4.20->4.21.

That's why I went back to using 4.18 because refresh there seems to work acceptable.

**Comment by atanisoft** [comment]
It's very possible there has been a change in the codebase that is causing the issue to occur more frequently.

**Comment by atanisoft** [comment]
@TrainzLuvr If you can run through some tests with this one again it would be appreciated. I've not seen this occurring with the latest code over either TWAI (CAN) or TCP/IP connections. I've only seen it disappear from JMRI for one or two seconds while the node(s) are processing the "validate node id" request and responses.

**Comment by TrainzLuvr** [comment]
In the past refershing the OpenLCB Network Tree window caused RX buffer overruns to pile up, but that is not happening anymore.

What happens now is that bus arb-err are climbing up.

The node still remains in the window, which is great though. Next I might try the latest JMRI version and see what happens with it.

**Comment by TrainzLuvr** [comment]
I put JMRI 4.20 up now - looks good, no lags in the window, nodes appear immediately.

After pressing Refresh half a dozen times, I notice that the arb-err climbed, obviously, but also heap has dropped.

```
[TWAI] RX:4169 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:3524,fail:0) bus (arb-err:1304,err:15,state:Running)
00:13:45.244: free heap: 180.97kB (max block size: 111.12kB), mainBufferPool: 4.88kB, task count: 17
[TWAI] RX:6141 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4501,fail:0) bus (arb-err:1965,err:15,state:Running)
00:14:00.246: free heap: 180.93kB (max block size: 111.12kB), mainBufferPool: 4.88kB, task count: 17
[TWAI] RX:6141 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:4501,fail:0) bus (arb-err:1965,err:15,state:Running)
[TWAI] RX:7628 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:5152,fail:0) bus (arb-err:2535,err:15,state:Running)
00:14:15.248: free heap: 178.36kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
[TWAI] RX:7629 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:5153,fail:0) bus (arb-err:2535,err:15,state:Running)
00:14:30.251: free heap: 178.36kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
[TWAI] RX:7629 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:5153,fail:0) bus (arb-err:2535,err:15,state:Running)
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
00:14:45.252: free heap: 178.36kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
```

It returned a bit few minutes later then went back down. Weird.

```
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
00:16:15.264: free heap: 178.37kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
00:16:30.266: free heap: 178.55kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
[TWAI] RX:9981 (pending:0,overrun:0,discard:0) TX:0 (pending:0,suc:6181,fail:0) bus (arb-err:3511,err:15,state:Running)
00:16:45.268: free heap: 178.37kB (max block size: 111.12kB), mainBufferPool: 6.80kB, task count: 17
```

**Comment by atanisoft** [comment]
The heap will fluctuate based on the TCP/IP stack usage (it's dynamically allocated). The usage shouldn't get too critical though.

The arb-err count going up likely is somewhat expected when nodes start talking simultaneously.

**Comment by TrainzLuvr** [comment]
Tried JMRI 4.21 now.

No hangs in the OpenLCB Network Tree window either so I would say the issue has been resolved (at least for now).

I have been using the IO board's LwIP values and not my own/OlcbHub ones, so perhaps an alignment to the IO board settings should be done, just in case.

**Comment by atanisoft** [comment]
Ok, I'll update the defaults on hub as well.

**Comment by atanisoft** [comment]
Fixed in https://github.com/atanisoft/esp32olcbhub/commit/000756e83b5ab59817af8f92aed4373f2339a45e
